[project]
name = "richin13-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pelican[markdown]>=4.11.0",
    "ruff>=0.9.10",
]
