name: Publish Pelican Blog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.x'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Install dependencies
      run: |
        uv sync --frozen

    - name: Build Pelican site
      run: pelican

    - name: Deploy to GitHub Pages
      run: |
        ghp-import output
        git push -f https://github.com/${{ github.repository }} gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
